server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:parkingdb;MODE=MYSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
