CREATE TABLE "userInfo" (
  "id" SERIAL PRIMARY KEY,
  "userName" varchar,
  "userId" varchar UNIQUE NOT NULL,
  "password" varchar NOT NULL,
  "organization" varchar,
  "role" varchar NOT NULL,
  "createdAt" timestamp
);

CREATE TABLE "humanDetectionReports" (
  "id" SERIAL PRIMARY KEY,
  "userID" varchar NOT NULL,
  "imageURL" varchar,
  "latitude" decimal,
  "longitude" decimal,
  "vehicleNumber" varchar,
  "reason" text,
  "status" varchar NOT NULL,
  "createdAt" timestamp
);

CREATE TABLE "autoDetectionReports" (
  "id" SERIAL PRIMARY KEY,
  "cctvId" long NOT NULL,
  "imageURL" varchar,
  "latitude" decimal,
  "longitude" decimal,
  "vehicleNumber" varchar,
  "status" varchar NOT NULL,
  "detectedBy" long,
  "ocrBy" long,
  "createdAt" timestamp
);

CREATE TABLE "detectionModels" (
  "id" SERIAL PRIMARY KEY,
  "version" varchar NOT NULL,
  "description" text,
  "model_url" varchar,
  "createdAt" timestamp
);

CREATE TABLE "routeRecommendationModels" (
  "id" SERIAL PRIMARY KEY,
  "version" varchar NOT NULL,
  "description" text,
  "model_url" varchar,
  "createdAt" timestamp
);

CREATE TABLE "OCRModels" (
  "id" SERIAL PRIMARY KEY,
  "name" varchar,
  "version" varchar NOT NULL,
  "description" text,
  "model_url" varchar,
  "createdAt" timestamp
);

CREATE TABLE "cctvInfo" (
  "id" SERIAL PRIMARY KEY,
  "latitude" decimal,
  "longitude" decimal,
  "purpose" varchar,
  "resolution" varchar,
  "isActive" boolean
);

CREATE TABLE "adminCode" (
  "code" varchar PRIMARY KEY NOT NULL
);

CREATE TABLE "routes" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "routes" json,
  "generatedBy" long,
  "generatedAt" timestamp
);

CREATE TABLE "parkingZones" (
  "id" SERIAL PRIMARY KEY,
  "name" varchar,
  "zonePolygon" json,
  "latitude" decimal,
  "longitude" decimal,
  "isRestricted" boolean,
  "updatedAt" timestamp
);

CREATE TABLE "loginLogs" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" integer NOT NULL,
  "loginTime" timestamp,
  "success" boolean
);

CREATE TABLE "reportLogs" (
  "id" SERIAL PRIMARY KEY,
  "reportType" varchar,
  "humanReportId" long,
  "autoReportId" long,
  "imageURL" varchar,
  "latitude" decimal,
  "longitue" decimal,
  "vehicleNumber" varchar,
  "previousStatus" varchar,
  "updatedStatus" varchar,
  "reportCreationTime" timestamp,
  "updatedAt" timestamp
);

COMMENT ON COLUMN "userInfo"."id" IS '고유일련번호';

COMMENT ON COLUMN "userInfo"."userName" IS '사용자이름, 20자 이내';

COMMENT ON COLUMN "userInfo"."userId" IS '사용자아이디';

COMMENT ON COLUMN "userInfo"."password" IS '8자리 이상 요구 필요, 암호화 저장';

COMMENT ON COLUMN "userInfo"."organization" IS '소속 조직';

COMMENT ON COLUMN "userInfo"."role" IS 'user, admin';

COMMENT ON COLUMN "humanDetectionReports"."id" IS '문서고유일련번호';

COMMENT ON COLUMN "humanDetectionReports"."userID" IS '사용자아이디';

COMMENT ON COLUMN "humanDetectionReports"."imageURL" IS '탐지 이미지 저장 위치; 탐지 이미지 실제 저장은 스토리지에 구성';

COMMENT ON COLUMN "humanDetectionReports"."latitude" IS '위치 좌표 위도; 지도 및 스마트폰 GPS 연동';

COMMENT ON COLUMN "humanDetectionReports"."longitude" IS '위치 좌표 경도; 지도 및 스마트폰 GPS 연동';

COMMENT ON COLUMN "humanDetectionReports"."vehicleNumber" IS '차량 번호, 암호화 저장';

COMMENT ON COLUMN "humanDetectionReports"."reason" IS '신고 이유';

COMMENT ON COLUMN "humanDetectionReports"."status" IS '등록됨, 처리중, 완료됨';

COMMENT ON COLUMN "autoDetectionReports"."id" IS '문서고유일련번호';

COMMENT ON COLUMN "autoDetectionReports"."cctvId" IS '탐지 CCTV 고유번호';

COMMENT ON COLUMN "autoDetectionReports"."imageURL" IS '탐지 이미지 저장 위치; 탐지 이미지 실제 저장은 스토리지에 구성';

COMMENT ON COLUMN "autoDetectionReports"."latitude" IS '탐지 (cctv) 위도';

COMMENT ON COLUMN "autoDetectionReports"."longitude" IS '탐지 (cctv) 경도';

COMMENT ON COLUMN "autoDetectionReports"."vehicleNumber" IS 'OCR 결과 차량 번호, 암호화 저장';

COMMENT ON COLUMN "autoDetectionReports"."status" IS '등록됨, 처리중, 완료됨';

COMMENT ON COLUMN "autoDetectionReports"."detectedBy" IS '탐지 모델 고유일련번호';

COMMENT ON COLUMN "autoDetectionReports"."ocrBy" IS 'OCR 모델 or 엔진 고유일련번호';

COMMENT ON COLUMN "detectionModels"."id" IS '탐지 모델 고유일련번호';

COMMENT ON COLUMN "detectionModels"."version" IS 'v1.0, v1.1 등';

COMMENT ON COLUMN "detectionModels"."description" IS '필요한 경우 설명 입력';

COMMENT ON COLUMN "detectionModels"."model_url" IS '모델 저장된 위치, 실제 저장은 스토리지에 구성';

COMMENT ON COLUMN "routeRecommendationModels"."id" IS '경로 추천 모델 (그래프 임베딩 모델 포함) 고유일련번호';

COMMENT ON COLUMN "routeRecommendationModels"."version" IS 'v1.0, v1.1 등';

COMMENT ON COLUMN "routeRecommendationModels"."description" IS '필요한 경우 설명 입력';

COMMENT ON COLUMN "routeRecommendationModels"."model_url" IS '모델 저장된 위치, 실제 저장은 스토리지에 구성';

COMMENT ON COLUMN "OCRModels"."id" IS '경로 추천 모델 (그래프 임베딩 모델 포함) 고유일련번호';

COMMENT ON COLUMN "OCRModels"."name" IS 'OCR 엔진 이름';

COMMENT ON COLUMN "OCRModels"."version" IS 'v1.0, v1.1 등';

COMMENT ON COLUMN "OCRModels"."description" IS '필요한 경우 설명 입력';

COMMENT ON COLUMN "OCRModels"."model_url" IS 'OCR 모델 경로 또는 API 엔드포인트';

COMMENT ON COLUMN "cctvInfo"."id" IS 'CCTV 고유번호';

COMMENT ON COLUMN "cctvInfo"."latitude" IS '위치 좌표 위도';

COMMENT ON COLUMN "cctvInfo"."longitude" IS '위치 좌표 경도';

COMMENT ON COLUMN "cctvInfo"."purpose" IS '설치 목적';

COMMENT ON COLUMN "cctvInfo"."resolution" IS 'cctv 화소 수';

COMMENT ON COLUMN "cctvInfo"."isActive" IS '운영 상태';

COMMENT ON COLUMN "adminCode"."code" IS '미리 저장 필요, 암호화 저장';

COMMENT ON COLUMN "routes"."routes" IS '지도 api용 경로 정보';

COMMENT ON COLUMN "routes"."generatedBy" IS '생성모델 ID / 탐색알고리즘 구현시 임베딩 모델 ID';

COMMENT ON COLUMN "parkingZones"."name" IS '도로명 or 구역명';

COMMENT ON COLUMN "parkingZones"."zonePolygon" IS '다각형 형태로 정의된 구역 좌표 배열 (위도/경도 쌍)';

COMMENT ON COLUMN "parkingZones"."latitude" IS '위치 좌표 위도';

COMMENT ON COLUMN "parkingZones"."longitude" IS '위치 좌표 경도';

COMMENT ON COLUMN "parkingZones"."isRestricted" IS '불법주정차 금지 구역 여부';

COMMENT ON COLUMN "loginLogs"."id" IS '로그관리번호';

COMMENT ON COLUMN "loginLogs"."userId" IS '사용자아이디';

COMMENT ON COLUMN "loginLogs"."success" IS '로그인 성공 여부';

COMMENT ON COLUMN "reportLogs"."reportType" IS 'human or auto 구분';

COMMENT ON COLUMN "reportLogs"."humanReportId" IS '수동 탐지 문서 고유 일련번호';

COMMENT ON COLUMN "reportLogs"."autoReportId" IS '자동 탐지 문서 고유 일련번호';

COMMENT ON COLUMN "reportLogs"."imageURL" IS '로깅 시점 정보 기록용';

COMMENT ON COLUMN "reportLogs"."latitude" IS '로깅 시점 정보 기록용';

COMMENT ON COLUMN "reportLogs"."longitue" IS '로깅 시점 정보 기록용';

COMMENT ON COLUMN "reportLogs"."vehicleNumber" IS '로깅 시점 정보 기록용';

COMMENT ON COLUMN "reportLogs"."previousStatus" IS '변경 전 상태';

COMMENT ON COLUMN "reportLogs"."updatedStatus" IS '변경 후 상태';

COMMENT ON COLUMN "reportLogs"."reportCreationTime" IS '첫 report 생성 시점; 로깅 시점 정보 기록용';

ALTER TABLE "humanDetectionReports" ADD FOREIGN KEY ("userID") REFERENCES "userInfo" ("userId");

ALTER TABLE "autoDetectionReports" ADD FOREIGN KEY ("cctvId") REFERENCES "cctvInfo" ("id");

ALTER TABLE "loginLogs" ADD FOREIGN KEY ("userId") REFERENCES "userInfo" ("id");

ALTER TABLE "routes" ADD FOREIGN KEY ("generatedBy") REFERENCES "routeRecommendationModels" ("id");

ALTER TABLE "autoDetectionReports" ADD FOREIGN KEY ("detectedBy") REFERENCES "detectionModels" ("id");

ALTER TABLE "autoDetectionReports" ADD FOREIGN KEY ("ocrBy") REFERENCES "OCRModels" ("id");

ALTER TABLE "reportLogs" ADD FOREIGN KEY ("humanReportId") REFERENCES "humanDetectionReports" ("id");

ALTER TABLE "reportLogs" ADD FOREIGN KEY ("autoReportId") REFERENCES "autoDetectionReports" ("id");
