spring:
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:~/parkingdb
        username: sa
        password: 1234
        platform: h2
        generate-unique-name: false
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
    h2:
        console:
            enabled: true
            path: /h2-console

    application:
        name: ParkingDetection

server:
    port: 8080
    servlet:
        encoding:
            force-response: true
logging:
    level:
        root: INFO
        com.aivle.ParkingDetection: DEBUG
jwt:
    secret: bXlzZWNyZXRrZXlmb3JzaWduaW5ndG9rZW5zMTIzNDU2