spring:
    datasource:
        driver-class-name: org.h2.Driver
                # Cause: The DB_CLOSE_ON_EXIT=FALSE setting prevents H2 from closing the database when the JVM exits.
        # This can cause database file lock issues, especially after an unclean shutdown.
        # Result: Removing this option ensures that database resources are properly released when the application stops.
        url: jdbc:h2:mem:testdb
        username: sa
        password: 1234
        platform: h2
        generate-unique-name: false
    jpa:
        hibernate:
            ddl-auto: create
        show-sql: true
        properties:
            hibernate:
                format_sql: true
    h2:
        console:
            enabled: true
            path: /h2-console

    application:
        name: ParkingDetection
    http:
        encoding:
            charset: UTF-8
            enabled: true
            force: true
    lifecycle:
        timeout-per-shutdown-phase: 10s

server:
    port: 8080
    servlet:
        encoding:
            force-response: true
    shutdown: graceful
    tomcat:
        # Ensure Tomcat shuts down properly
        connection-timeout: 20000
        threads:
            max: 200
            min-spare: 10
logging:
    level:
        root: INFO
        com.aivle.ParkingDetection: DEBUG
jwt:
    secret: bXlzZWNyZXRrZXlmb3JzaWduaW5ndG9rZW5zMTIzNDU2
