spring:
    datasource:
        url: jdbc:mysql://localhost:3306/parking?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=utf8
        username: parking_user
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
            maximum-pool-size: 15
            minimum-idle: 5
            idle-timeout: 600000
            max-lifetime: 1800000
            connection-timeout: 30000
    jpa:
        hibernate:
            ddl-auto: create      # 개발 중: update / 운영: validate 권장
        properties:
            hibernate:
                format_sql: true
                dialect: org.hibernate.dialect.MySQL8Dialect
                jdbc.time_zone: Asia/Seoul
        open-in-view: false

    jackson:
        time-zone: Asia/Seoul

logging:
    level:
        org.hibernate.SQL: debug
        org.hibernate.orm.jdbc.bind: trace
